LangString addOrReinstall ${LANG_POLISH} "Napraw / zainstaluj ponownie składniki"
LangString alreadyInstalled ${LANG_POLISH} "Wykryto istniejącą instalację"
LangString alreadyInstalledLong ${LANG_POLISH} "${PRODUCTNAME} ${VERSION} jest już zainstalowany. Wybierz operację i kliknij Dalej."
LangString appRunning ${LANG_POLISH} "${PRODUCTNAME} jest uruchomiony. Zamknij program i spróbuj ponownie."
LangString appRunningOkKill ${LANG_POLISH} "${PRODUCTNAME} jest uruchomiony.$\nKliknij OK, aby zakończyć jego proces."
LangString chooseMaintenanceOption ${LANG_POLISH} "Wybierz aktualizację, naprawę albo odinstalowanie."
LangString choowHowToInstall ${LANG_POLISH} "Wybierz sposób instalacji ${PRODUCTNAME}."
LangString createDesktop ${LANG_POLISH} "Utwórz skrót na pulpicie"
LangString dontUninstall ${LANG_POLISH} "Aktualizuj w miejscu (zachowaj dane i katalog)"
LangString dontUninstallDowngrade ${LANG_POLISH} "Nie odinstalowuj (downgrade bez odinstalowania jest zablokowany)"
LangString failedToKillApp ${LANG_POLISH} "Nie udało się zakończyć ${PRODUCTNAME}. Zamknij program ręcznie i spróbuj ponownie."
LangString installingWebview2 ${LANG_POLISH} "Instalowanie WebView2..."
LangString newerVersionInstalled ${LANG_POLISH} "Zainstalowana jest nowsza wersja ${PRODUCTNAME}. Downgrade jest domyślnie zablokowany. Użyj nowszego instalatora albo odinstaluj obecną wersję przed świadomą instalacją starszej."
LangString older ${LANG_POLISH} "starsza"
LangString olderOrUnknownVersionInstalled ${LANG_POLISH} "Wykryto $R4 wersję ${PRODUCTNAME}. Możesz zaktualizować program w istniejącym katalogu albo najpierw odinstalować poprzednią wersję. Dane spraw i konfiguracja użytkownika pozostają poza katalogiem programu."
LangString silentDowngrades ${LANG_POLISH} "Downgrade jest zablokowany dla tego instalatora.$\n"
LangString unableToUninstall ${LANG_POLISH} "Nie udało się odinstalować programu."
LangString uninstallApp ${LANG_POLISH} "Odinstaluj ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_POLISH} "Odinstaluj poprzednią wersję przed instalacją"
LangString unknown ${LANG_POLISH} "nieznana"
LangString webview2AbortError ${LANG_POLISH} "Nie udało się zainstalować WebView2. Program wymaga tego składnika. Uruchom instalator ponownie."
LangString webview2DownloadError ${LANG_POLISH} "Błąd pobierania WebView2: $0"
LangString webview2DownloadSuccess ${LANG_POLISH} "Pobrano instalator WebView2"
LangString webview2Downloading ${LANG_POLISH} "Pobieranie WebView2..."
LangString webview2InstallError ${LANG_POLISH} "Instalacja WebView2 nie powiodła się. Kod: $1"
LangString webview2InstallSuccess ${LANG_POLISH} "WebView2 zainstalowano poprawnie"
LangString deleteAppData ${LANG_POLISH} "Usuń także dane aplikacji"
